blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/strongloop/loopback-next/discussions
    about: Please ask and answer questions here.
  - name: Get help on StackOverflow
    url: https://stackoverflow.com/tags/loopbackjs
    about: Please ask and answer questions on StackOverflow.
  - name: Join our mailing list
    url: https://groups.google.com/forum/#!forum/loopbackjs
    about: You can also post your question to our mailing list.
